defmodule Gateflow.Project.Repo.Migrations.AddBoardsAndFlowItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:flowitems, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :flow_item_id, :uuid, null: false
      add :title, :text
      add :state, :text, null: false, default: "not_blocked"
      add :board_id, :uuid
    end

    create table(:boards, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
    end

    alter table(:flowitems) do
      modify :board_id,
             references(:boards,
               column: :id,
               prefix: "public",
               name: "flowitems_board_id_fkey",
               type: :uuid
             )
    end

    alter table(:boards) do
      add :name, :text
    end
  end

  def down do
    alter table(:boards) do
      remove :name
    end

    drop constraint(:flowitems, "flowitems_board_id_fkey")

    alter table(:flowitems) do
      modify :board_id, :uuid
    end

    drop table(:boards)

    drop table(:flowitems)
  end
end