defmodule Gateflow.Project.Repo.Migrations.AddInsertedAtAndRootBool do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:flowitems) do
      add :is_root, :boolean, default: false
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    alter table(:boards) do
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    alter table(:boards) do
      remove :inserted_at
    end

    alter table(:flowitems) do
      remove :inserted_at
      remove :is_root
    end
  end
end